@startuml
GameRunLoop o-- GameStateManager
GameStateManager o-- MapManager
GameStateManager o-- TransportManager

TransportManager o-- MapManager
TransportManager o-- BreadthFirstSearchRouting

HexagonNeighbourCalculator o-- MapManager

BreadthFirstSearchRouting o-- MapManager
BreadthFirstSearchRouting o-- HexagonNeighbourCalculator
@enduml