@startuml
GameRunLoop o-- GameStateManager
GameStateManager o-- MapManager
GameStateManager o-- TransportManager

TransportManager o-- MapManager
TransportManager o-- BreadthFirstSearchRouting

@enduml